{% set name = "zellij" %}
{% set version = "0.41.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/zellij-org/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 12e7f0f80c1e39deed5638c4662fc070855cee0250a7eb1d76cefbeef8c2f376

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - make

test:
  commands:
    - {{ name }} --help

about:
  home: https://zellij.dev
  license: MIT
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml
  summary: Pluggable terminal workspace, with terminal multiplexer as the base feature
  dev_url: https://github.com/{{ name }}-org/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
