context:
  version: "0.42.0"

package:
  name: zellij
  version: ${{ version }}

source:
  url: https://github.com/zellij-org/zellij/archive/v${{ version }}.tar.gz
  sha256: 35f620f8aca7128047e8be520c88514156c8249763cfbc103107499dd2052f2a

build:
  number: 0
  skip: win
  prefix_detection:
    ignore_binary_files: true

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - make
    - libprotobuf
    - pkg-config
  host:
    - curl
    - libcurl

tests:
  - script:
      - zellij --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml
  summary: Pluggable terminal workspace, with terminal multiplexer as the base feature
  homepage: https://zellij.dev
  repository: https://github.com/zellij-org/zellij

extra:
  recipe-maintainers:
    - danielnachun
