context:
  version: 0.41.2

package:
  name: zellij
  version: ${{ version }}

source:
  url: https://github.com/zellij-org/zellij/archive/v${{ version }}.tar.gz
  sha256: 12e7f0f80c1e39deed5638c4662fc070855cee0250a7eb1d76cefbeef8c2f376

build:
  number: 2
  skip: win
  prefix_detection:
    ignore_binary_files: true

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - make
    - libprotobuf
    - pkg-config
  host:
    - curl
    - libcurl

tests:
  - script:
      - zellij --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml
  summary: Pluggable terminal workspace, with terminal multiplexer as the base feature
  homepage: https://zellij.dev
  repository: https://github.com/zellij-org/zellij

extra:
  recipe-maintainers:
    - danielnachun
