context:
  version: "0.45.1"

package:
  name: zellij
  version: ${{ version }}

source:
  url: https://github.com/zellij-org/zellij/archive/v${{ version }}.tar.gz
  sha256: 5cbe711437d2a61afd9287165f6aca0bcccb9ab1473633665a5b11ed55467852

build:
  number: 0
  skip: win
  prefix_detection:
    ignore_binary_files: true

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - make
    - libprotobuf
    - pkg-config
  host:
    - curl
    - libcurl

tests:
  - script:
      - zellij --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml
  summary: Pluggable terminal workspace, with terminal multiplexer as the base feature
  homepage: https://zellij.dev
  repository: https://github.com/zellij-org/zellij

extra:
  recipe-maintainers:
    - danielnachun
